### PR TITLE
Allow embedded collections

### LINKED ISSUE #38: Allow API access to minimal structure declaration
Reported by @alyxrossetti.

*Issue*
Collections like multi-volume works or collections that don't have their own unique identity should be embedded within a parent collection. Currently there is no way to generate a serialization that embeds these.

*Analysis*
There is no (non-kludgey) access to the `minimal` flag in `_structure_properties`.
There /is/ some access via the `_should_be_minimal()` function, but would require some crazy monkey patching on specific Collection instances.  

*Proposed Solution*
Implement `Collection::_should_be_minimal()` to check if the child collection should be embedded, by checking a `embed` flag on the child.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #38

### CODE REVIEW

**Comment by azaroth42** [comment]
Seriously... wtf?
```
[rsanderson@GT26940 iiif-prezi (minimal-api)]$ pep8 --ignore=E501 *.py iiif_prezi/*.py examples/*.py tests/*.py
tests/test_factory.py:71:73: W292 no newline at end of file

// adds newline at end of file

[rsanderson@GT26940 iiif-prezi (minimal-api)]$ pep8 --ignore=E501 *.py iiif_prezi/*.py examples/*.py tests/*.py
tests/test_factory.py:72:1: W293 blank line contains whitespace
tests/test_factory.py:72:1: W391 blank line at end of file
```

**Comment by zimeon** [comment]
PEP8 loves you and wants you to be happy... but only its way

**Comment by azaroth42** [comment]
PEP8 shouldn't want to change me! 😀

**Comment by zimeon** [comment]
Once you are good, it won't ;-)

**Pull request merged**
